### ISSUE TITLE
Mobile Accessibility Issue

### ISSUE THREAD

**Issue by jakewtaylor** [jakewtaylor/my-site-remix#2]
The mobile-only button that expands the current track viewer does not contain any text, just an SVG. This is flagged as an accessibility issue;

- Add an `aria-label` attribute to the button to fix this
  - Give it a value of "See currently playing track" or something to that effect?

[This is the button in question](https://github.com/jakewtaylor/my-site-remix/blob/0d7240865abfd77b100efdb2620869882a17ac21/app/components/Sidebar/index.tsx#L88), appears in the bottom navbar on mobile:

<img width="67" alt="image" src="https://user-images.githubusercontent.com/8126758/194276408-1149cfa6-4abf-4938-aa89-03396a5930af.png">

**Comment by kala2** [comment]
hey, can i take this one?

**Comment by jakewtaylor** [comment]
Go for it! Thanks 😄

**Comment by kala2** [comment]
Hey, opened PR #5
