### ISSUE TITLE
Incorrect Heading Accessibility Issue

### ISSUE THREAD

**Issue by jakewtaylor** [jakewtaylor/my-site-remix#3]
The "Hey, my name is" text is a `<h5>` tag, that precedes the "Jake Taylor" text which is a `<h1>` tag.

Heading tags should only go down in size as the page flows - i.e. `h5` before `h1` is bad practice.

The `h5` tag here should probably just be a `p`.

**Comment by Vani177** [comment]
hey, i can solve this issue, can you please assign it to me?

**Comment by jakewtaylor** [comment]
Hey @Vani177, there you go! Thanks a lot 😄

**Comment by Vani177** [comment]
Glad to help! 😊
