### ISSUE TITLE
"Currently playing" text contrast accessibility issues

### ISSUE THREAD

**Issue by jakewtaylor** [jakewtaylor/my-site-remix#6]
Lighthouse and axe both pick up on text contrast issues with the "LISTENING NOW" text in this section of the site:

<img width="198" alt="image" src="https://user-images.githubusercontent.com/8126758/194333889-7a07dae0-d49a-4e9c-8419-4698b9adc73e.png">

Needs to be changed to improve contrast.

If you want to pick up this issue, feel free to do so, just drop a comment and I'll assign you!

**Comment by jakewtaylor** [comment]
You can use the lighthouse dev tools to run an assessment and see this for yourself. Alternatively, the built in browser dev tools tend to show a contrast score when you use the inspector cursor and hover over the text:

- <img width="24" alt="image" src="https://user-images.githubusercontent.com/8126758/194334826-8b6b2bec-55af-4271-aae9-7217e914de02.png">
- <img width="265" alt="image" src="https://user-images.githubusercontent.com/8126758/194334867-45b424da-5c78-4e42-9a9c-f908e4521f69.png">

I'm currently getting a contrast ratio of 3.01, I believe 4.5 is the target.

**Comment by DanielSadler** [comment]
I accept the challenge!
